export const D={
 name:"Muhammad Saad",email:"muhammadsaadgu@gmail.com",phone:"+923160928247",loc:"Islamabad, Pakistan",
 roles:["Senior .NET Full Stack Developer","React.js & .NET Engineer","ASP.NET Core 10 & Blazor Developer","REST API & Database Specialist"],
 sum:"Senior .NET Full-Stack Developer with 3+ years of professional experience building scalable web applications using C#, ASP.NET Core, React.js, Node.js, Entity Framework Core, and SQL Server. I turn business requirements into reliable, secure and maintainable solutions, and collaborate with cross-functional teams throughout the software development lifecycle.",
 stats:[["3+","Years Experience"],["6","Major Projects"],["2","Companies"],["30+","Technologies"]],
 high:["Enterprise apps with ASP.NET Core 10, Blazor & React.js","Clean Architecture, CQRS, Vertical Slice & MediatR","Secure REST APIs, JWT, OAuth 2.0, OpenID Connect & RBAC","Real-time apps with SignalR, Socket.io & WebSockets","Database design, indexing & query optimization","Cross-functional team collaboration across the full SDLC"],
 skills:{
  "Frontend":["HTML5","CSS3","JavaScript (ES6+)","TypeScript","React.js","Blazor","Redux Toolkit","Context API","Tailwind CSS","Bootstrap","Material UI","SASS/SCSS","Vite","Webpack","npm","PWA","Service Workers","Figma","Adobe XD"],
  "Backend":["C#","ASP.NET Core 10","Web API","Node.js","Express.js","Microservices","Entity Framework Core","LINQ","Migrations","SignalR","Socket.io","WebSockets","Dependency Injection","Middleware"],
  "Database":["SQL Server","PostgreSQL","MongoDB","Database Design","Indexing","Query Optimization"],
  "Security & Auth":["JWT","OAuth 2.0","OpenID Connect","ASP.NET Identity","RBAC","API Security","Validation","Error Handling"],
  "Architecture & Practices":["Clean Architecture","CQRS","Vertical Slice Architecture","MediatR","SOLID","Design Patterns","Caching","Async Programming","Lazy Loading","Code Splitting","Payment Gateways","Cloud Storage APIs"]},
 exp:[
  {y:"January 2025 – Present",r:"Senior .NET Full Stack Developer",c:"Cloud QuickCompany",b:["Developed scalable enterprise web applications using C#, ASP.NET Core, Entity Framework Core, and SQL Server","Built reusable UI component libraries with React.js to improve development efficiency and maintainability","Designed and integrated secure RESTful APIs using ASP.NET Core Web API with JWT authentication and role-based authorization","Optimized frontend performance using lazy loading, code splitting, and caching techniques","Integrated third-party services including payment gateways, analytics, and cloud storage APIs","Collaborated with UI/UX teams to implement responsive, pixel-perfect user interfaces","Improved application performance and reduced API response time through SQL query optimization and indexing"],t:["C#","ASP.NET Core","EF Core","SQL Server","React.js","JWT","RBAC"]},
  {y:"June 2023 – January 2025",r:"MERN Stack Developer",c:"Ewarenet Company",b:["Developed responsive web applications using React.js and Tailwind CSS","Built backend services and APIs using Node.js and Express.js","Worked with MongoDB for schema design, aggregation pipelines, and data optimization","Implemented authentication and authorization using JWT and OAuth","Developed real-time notification systems using Socket.io","Integrated REST APIs and external services for seamless application functionality","Collaborated with cross-functional teams to deliver high-quality software solutions"],t:["React.js","Node.js","Express.js","MongoDB","Socket.io","OAuth","Tailwind CSS"]}],
 proj:[
  {n:"Netrex E-Commerce",k:"E-Commerce · Blazor",g:"#6366f1,#ec4899",
   d:"A full-featured, scalable e-commerce platform built with ASP.NET Core 10 and a Blazor frontend, structured with Clean Architecture so the domain, application, infrastructure and UI layers stay independent, testable and easy to extend.",
   h:["Product catalog with categories, search, filtering and inventory management","Shopping cart, secure checkout, order lifecycle and payment gateway integration","Admin dashboard for products, orders, customers and sales reporting","JWT authentication, ASP.NET Identity and role-based access for admins and customers","Clean Architecture with CQRS and MediatR; EF Core with optimized SQL Server queries"],
   t:["C#","ASP.NET Core 10","Blazor","Clean Architecture","CQRS","MediatR","Entity Framework Core","SQL Server","JWT"]},
  {n:"Online Complaint Management System (OCMS)",k:"Public Service · React.js",g:"#0ea5e9,#10b981",
   d:"A complete online complaint management platform where citizens or customers can lodge complaints, track progress and receive updates, while staff route, resolve and escalate them. Built with an ASP.NET Core 10 Web API following Clean Architecture and a responsive React.js frontend.",
   h:["Complaint submission with categories, priority levels and file attachments","Automatic assignment and routing to departments and officers, with escalation of overdue cases","Real-time status tracking and notifications for complainants and staff","Role-based dashboards and reports for admins, officers and complainants","Clean Architecture, JWT authentication, RBAC and EF Core with SQL Server"],
   t:["C#","ASP.NET Core 10","Web API","React.js","Clean Architecture","Entity Framework Core","SQL Server","JWT","RBAC"]},
  {n:"Litigation Tracking System (LTS)",url:"https://nisaadtech.com",k:"Legal Tech · Blazor",g:"#8b5cf6,#6366f1",
   d:"A scalable litigation platform for managing cases, hearings, documents, deadlines and case activities, with interactive Blazor dashboards for tracking cases and legal workflows.",
   h:["Case management for parties, assignments, milestones, hearings, notes and documents","Secure ASP.NET Core Web APIs with JWT authentication and role-based authorization","CQRS, Vertical Slice Architecture and MediatR for clean, maintainable backend design"],
   t:["C#","ASP.NET Core","Web API","EF Core","SQL Server","Blazor","CQRS","MediatR","JWT"]},
  {n:"Vaccination Management System",k:"Healthcare",g:"#0ea5e9,#6366f1",
   d:"Secure .NET Core APIs for vaccine inventory, scheduling and patient records, with a React.js frontend for appointment booking and vaccination tracking, plus dashboards and reports driven by optimized queries.",
   h:["Role-based access control for admins, doctors and patients","Performance improved with efficient API design and caching"],
   t:[".NET Core","Entity Framework","React.js","SQL Server","JWT","Bootstrap","Material UI"]},
  {n:"Hospital Management System",k:"Healthcare",g:"#10b981,#0ea5e9",
   d:"A modular hospital system covering patient management, appointments, EMR, billing and pharmacy, with role-based dashboards for admins, doctors, staff and patients, and reporting and analytics built on SQL.",
   h:["Scalable backend following clean code practices","Secure data handling with authentication and authorization"],
   t:[".NET","React.js","Entity Framework","PostgreSQL","Bootstrap"]},
  {n:"EventCombo – Event Management",k:"Event Management",g:"#f59e0b,#ef4444",
   d:"A full-featured MERN event platform with event scheduling, ticket booking, attendee and vendor management, payment tracking and reporting, plus review and feedback modules, built to support high concurrent users.",
   h:["Responsive, user-friendly interfaces with React.js and Tailwind CSS"],
   t:[".NET","React.js","Entity Framework","MongoDB","Tailwind CSS","Material UI"]}],
 svc:[["Backend Development","Scalable REST APIs and server-side logic with ASP.NET Core, Node.js and Express.js."],[".NET Development","Enterprise applications with C#, ASP.NET Core 10, EF Core and Clean Architecture."],["Blazor Development","Interactive web UIs and dashboards built with Blazor and C#."],["React Development","Responsive SPAs with React, Redux Toolkit, TypeScript and reusable components."],["Auth & Security","JWT, OAuth 2.0, OpenID Connect, ASP.NET Identity and RBAC."],["Real-Time Apps","Live notifications and updates with SignalR, Socket.io and WebSockets."],["Database Design","SQL Server, PostgreSQL and MongoDB design, indexing and optimization."],["Integrations","Payment gateways, cloud storage and third-party service integration."]]
};
export const NAV=["Home","About","Skills","Experience","Projects","Services","Contact"];
