export const D={
 name:"Muhammad Saad",email:"muhammadsaad3877gu@gmail.com",phone:"+923160928247",loc:"Islamabad, Pakistan",
 roles:["Senior .NET Full Stack Developer","React.js & .NET Engineer","REST API & Database Specialist"],
 sum:"Senior .NET Full-Stack Developer with 4+ years of professional experience building scalable web applications using C#, ASP.NET Core, React.js, Node.js, Entity Framework Core, and SQL Server. I turn business requirements into reliable, secure and maintainable solutions.",
 stats:[["4+","Years Experience"],["4","Major Projects"],["2","Companies"],["30+","Technologies"]],
 high:["Enterprise apps with .NET & React.js","Secure REST APIs, JWT, OAuth 2.0 & RBAC","Real-time apps with SignalR & Socket.io","Database design, indexing & query tuning","Clean architecture, SOLID & dependency injection","Cross-functional team collaboration"],
 skills:{
  "Frontend":["HTML5","CSS3","JavaScript (ES6+)","TypeScript","React.js","Redux Toolkit","Context API","Tailwind CSS","Bootstrap","Material UI","SASS/SCSS","Vite","Webpack","PWA","Figma","Adobe XD"],
  "Backend":["C#","ASP.NET Core","Web API","Node.js","Express.js","Microservices","Entity Framework Core","LINQ","SignalR","Socket.io","WebSockets","Dependency Injection"],
  "Database":["SQL Server","PostgreSQL","MongoDB","Database Design","Indexing","Query Optimization"],
  "Security & Auth":["JWT","OAuth 2.0","OpenID Connect","ASP.NET Identity","RBAC","API Security","Validation"],
  "Architecture & Practices":["Clean Architecture","SOLID","Design Patterns","Caching","Lazy Loading","Code Splitting","Payment Gateways","Cloud Storage APIs"]},
 exp:[
  {y:"April 2024 – Present",r:"Senior .NET Full Stack Developer",c:"Cloud QuickCompany",b:["Developed scalable enterprise web applications using React.js, Node.js, Express.js, and MongoDB","Built reusable UI component libraries to improve efficiency and maintainability","Designed secure RESTful APIs with JWT authentication and role-based authorization","Optimized frontend performance with lazy loading, code splitting, and caching","Integrated payment gateways, analytics, and cloud storage APIs","Reduced API response time through database query optimization"],t:["React.js","Node.js","Express.js","MongoDB","JWT","RBAC"]},
  {y:"May 2022 – March 2024",r:"MERN Stack Developer",c:"Ewarenet Company",b:["Developed responsive web apps using React.js and Tailwind CSS","Built backend services and APIs using Node.js and Express.js","Designed MongoDB schemas and aggregation pipelines","Implemented authentication with JWT and OAuth","Developed real-time notifications using Socket.io","Collaborated with cross-functional teams to deliver quality software"],t:["React.js","Node.js","MongoDB","Socket.io","OAuth","Tailwind CSS"]}],
 proj:[
  {n:"Vaccination Management System",k:"Healthcare",i:"💉",g:"#6366f1,#0ea5e9",d:"Secure APIs for vaccine inventory, scheduling and patient records, with appointment booking, vaccination tracking and RBAC for admins, doctors and patients.",t:["Dotnet Core","Entity Framework","React.js","SQL Server","JWT","Bootstrap","Material UI"]},
  {n:"Healthcare Management Platform",k:"Healthcare",i:"🏥",g:"#0ea5e9,#10b981",d:"Platform for managing patients, doctors and billing with interactive React dashboards, secure auth, real-time updates via WebSockets and optimized database performance.",t:["Node.js","MongoDB","SQL Server","React.js","Tailwind CSS","JWT","WebSockets"]},
  {n:"Hospital Management System",k:"Healthcare",i:"🩺",g:"#8b5cf6,#ec4899",d:"Modular system covering patient management, appointments, EMR, billing and pharmacy, with role-based dashboards and reporting built on clean architecture.",t:["Dotnet Core","React.js","Entity Framework","PostgreSQL","Bootstrap"]},
  {n:"EventCombo – Event Management",k:"Event Management",i:"🎟️",g:"#f59e0b,#ef4444",d:"Full-featured event platform with scheduling, ticket booking, attendee and vendor management, payment tracking, reviews and feedback, built for high concurrency.",t:["Dotnet","React.js","Entity Framework","MongoDB","Tailwind CSS","Material UI"]}],
 svc:[["⚙️","Backend Development","Scalable REST APIs and server-side logic with ASP.NET Core, Node.js and Express.js."],["🧩",".NET Development","Enterprise applications with C#, EF Core and clean architecture."],["⚛️","React Development","Responsive SPAs with React, Redux Toolkit, TypeScript and reusable components."],["🔐","Auth & Security","JWT, OAuth 2.0, OpenID Connect, ASP.NET Identity and RBAC."],["⚡","Real-Time Apps","Live notifications and updates with SignalR, Socket.io and WebSockets."],["🗄️","Database Design","SQL Server, PostgreSQL and MongoDB design, indexing and optimization."],["🚀","Performance Tuning","Caching, lazy loading, code splitting and query optimization."],["🔌","Integrations","Payment gateways, cloud storage and third-party service integration."]]
};
export const NAV=["Home","About","Skills","Experience","Projects","Services","Contact"];
